<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\..\..\..\..\Downloads\pc.png" Link="wwwroot\pc.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.10" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AGRIMARKET.APPLICATION\AGRIMARKET.APPLICATION.csproj" />
    <ProjectReference Include="..\AGRIMARKET.INFRASTRUCTURE\AGRIMARKET.INFRASTRUCTURE.csproj" />
    <ProjectReference Include="..\AGRIMARKET.RESOURCES\AGRIMARKET.RESOURCES.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\assets\" />
  </ItemGroup>

</Project>
