// <auto-generated />
using System;
using AGRIMARKET.INFRASTRUCTURE.INFRA.CONTEXT;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AGRIMARKET.INFRASTRUCTURE.Migrations
{
    [DbContext(typeof(AgriMarketContext))]
    [Migration("20260916210211_initial1")]
    partial class initial1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AGRIMARKET.DOMAIN.DOMAIN.MODELS.MODEL.MKT.CommodityModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Commodities");
                });

            modelBuilder.Entity("AGRIMARKET.DOMAIN.DOMAIN.MODELS.MODEL.MKT.MarketModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("DistrictId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("Markets");
                });

            modelBuilder.Entity("AGRIMARKET.DOMAIN.DOMAIN.MODELS.MODEL.MKT.PriceModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CommodityId")
                        .HasColumnType("bigint");

                    b.Property<int>("Curreny")
                        .HasColumnType("int");

                    b.Property<long?>("MarketId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("MaxPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("PriceSourceId")
                        .HasColumnType("bigint");

                    b.Property<int>("PriceType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("SourceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CommodityId");

                    b.HasIndex("MarketId");

                    b.HasIndex("PriceSourceId");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("AGRIMARKET.DOMAIN.DOMAIN.MODELS.MODEL.MKT.PriceSource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("AGRIMARKET.DOMAIN.DOMAIN.MODELS.MODEL.STR.DistrictModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RegionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("AGRIMARKET.DOMAIN.DOMAIN.MODELS.MODEL.STR.RegionModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("AGRIMARKET.DOMAIN.DOMAIN.MODELS.MODEL.MKT.MarketModel", b =>
                {
                    b.HasOne("AGRIMARKET.DOMAIN.DOMAIN.MODELS.MODEL.STR.DistrictModel", "District")
                        .WithMany("Markets")
                        .HasForeignKey("DistrictId");

                    b.Navigation("District");
                });

            modelBuilder.Entity("AGRIMARKET.DOMAIN.DOMAIN.MODELS.MODEL.MKT.PriceModel", b =>
                {
                    b.HasOne("AGRIMARKET.DOMAIN.DOMAIN.MODELS.MODEL.MKT.CommodityModel", "Commodity")
                        .WithMany("Prices")
                        .HasForeignKey("CommodityId");

                    b.HasOne("AGRIMARKET.DOMAIN.DOMAIN.MODELS.MODEL.MKT.MarketModel", "Market")
                        .WithMany("Prices")
                        .HasForeignKey("MarketId");

                    b.HasOne("AGRIMARKET.DOMAIN.DOMAIN.MODELS.MODEL.MKT.PriceSource", "PriceSource")
                        .WithMany("Prices")
                        .HasForeignKey("PriceSourceId");

                    b.Navigation("Commodity");

                    b.Navigation("Market");

                    b.Navigation("PriceSource");
                });

            modelBuilder.Entity("AGRIMARKET.DOMAIN.DOMAIN.MODELS.MODEL.STR.DistrictModel", b =>
                {
                    b.HasOne("AGRIMARKET.DOMAIN.DOMAIN.MODELS.MODEL.STR.RegionModel", "Region")
                        .WithMany("Districts")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("AGRIMARKET.DOMAIN.DOMAIN.MODELS.MODEL.MKT.CommodityModel", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("AGRIMARKET.DOMAIN.DOMAIN.MODELS.MODEL.MKT.MarketModel", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("AGRIMARKET.DOMAIN.DOMAIN.MODELS.MODEL.MKT.PriceSource", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("AGRIMARKET.DOMAIN.DOMAIN.MODELS.MODEL.STR.DistrictModel", b =>
                {
                    b.Navigation("Markets");
                });

            modelBuilder.Entity("AGRIMARKET.DOMAIN.DOMAIN.MODELS.MODEL.STR.RegionModel", b =>
                {
                    b.Navigation("Districts");
                });
#pragma warning restore 612, 618
        }
    }
}
